# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - npm-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - npm-dependencies-

      - run: npm install

      - save_cache:
          name: Save npm packages to cache
          key: npm-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      # run tests!
      - run: npm test
